App1/urls.py
from django.urls import path
from . import views

app_name='App1'

urlpatterns=[
    path('home',views.home,name='home'),
    path('about',views.about,name='about'),
    path('contact',views.contact,name='contact'),
    
]

project1/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('App1/',include('App1.urls')),
]

App1/models.py
from django.db import models

# Create your models here.

App1/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'homepages/home.html')

def about(request):
    return render(request,'homepages/about.html')

def contact(request):
    return render(request,'homepages/contact.html')

App1/templates/homepages/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>ABOUT US</h2>
    <h2>ABOUT US</h2>
    
</body>
</html>

App1/templates/homepages/amal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>amal</h1>
</body>
</html>

App1/templates/homepages/babtra.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <h1>mufeedamkf</h1> 
</body>
</html>

App1/templates/homepages/contact.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h2>CONTACT US</h2>
    <form action="">
        <label for="">name</label>
        <input type="text">
        <label for="">date of birth</label>
        <input type="date">
    </form>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Iure recusandae quae quos neque vero quidem quo
        voluptas officiis, repellendus excepturi pariatur corporis ab ut aperiam totam, velit omnis molestias.
        Asperiores.</p>
</body>

</html>

App1/templates/homepages/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro nobis laboriosam tempora dolorem ipsam. Eos quaerat voluptatem sed quia magni numquam omnis, adipisci, fuga veniam inventore, voluptatum consectetur hic quibusdam?</p>
   
   
    <h2>BAABTRA</h2> 
    <a href="{% url 'App1:home' %}">HOME</a>
    <a href="{% url 'App1:about' %}">ABOOUT</a>
    <a href="{% url 'App1:contact' %}">CONTACT</a> <hr>
</body>
</html>

App1/templates/homepages/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    update from fidal
</body>
</html>

App1/templates/homepages/page1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>flipkart</h1>
</body>
</html>